### ISSUE TITLE
How to use Microprofile config with system environments?

### ISSUE THREAD

**Issue by ThomasSousa96** [payara/Payara#3119]
# Description #
I'm using Payara Micro with Eclipse Micro Profile, but i desire override the value of a config property using system environment.

## Samples
I define a property using CDI:
```java
    @Inject
    @ConfigProperty(name = "sample.config.bar", defaultValue = "0")
    private long bar;
```
Docker compose
```
version: '3.6'

services:
  backend:
    image: payara/micro:5.182
    networks:
      - backend
    ports:
      - 8081:8080
      - 8182:8181
      - 5900:5900
   environment:
      SAMPLE_CONFIG_BAR: 10
    volumes:
      - ./services/backend/applications:/opt/payara/deployments
    restart: on-failure
```
When i run the application the `sample.config.bar` property value is zero, but in the docker compose i define the `SAMPLE_CONFIG_BAR` environment. What is necessary do to enable the system environment in the eclipse microprofile config?

## Environment ##
- **Payara Version**: 5.182
- **Edition**: Micro
- **JDK Version**:  8 OpenJDK
- **Operating System**: Linux
