### ISSUE TITLE
Nested Lists annotation

### ISSUE THREAD

**Issue by EmirAde** [payara/Payara#4218]
# Description #
----------

Hi,

I have trouble with the openapi-microprofile implementation in Payara-5.184
is it possible to annotate a nested array with @Schema? 

## Expected Outcome

Example:
```
@Schema(implementation = String[].class, type = SchemaType.ARRAY, description = "Some description.")
private List<List<String>> configurations;
```

The resulting json should be like this:
```
configurations:
    description: Some description
    type: array
    items: 
        type: array
        items:
            type: string
```

## Current Outcome

Example:
```
@Schema(implementation = String[].class, type = SchemaType.ARRAY, description = "Some description.")
private List<List<String>> configurations;
```

The resulting json looks like this:
```
configurations:
    type: array
    description: Some description
    items: {}
```

## Environment ##

- **Payara Version**: 5.194
- **Edition**: Full
- **JDK Version**: 8u181 Oracle
- **Operating System**: Mac

Application **pom.xml**:
```
<groupId>org.eclipse.microprofile.openapi</groupId>
      <artifactId>microprofile-openapi-api</artifactId>
<version>1.0.1</version>
```
