### ISSUE TITLE
Support for Istio with mTLS

### ISSUE THREAD

**Issue by yacut** [payara/Payara#4326]
# Description #
Payara Micro does not work in k8s cluster mode if Istio with mTLS installed.
Related to https://github.com/hazelcast/hazelcast-kubernetes/issues/118

## Expected Outcome
Payara cluster in k8s mode starts two instances with Istio sidecar without any issue.

## Current Outcome

An error occurred on second payara micro node:
```sh
$ kubectl logs -f payara-micro-1 payara-micro
...
[2019-11-15T08:00:04.375+0000] [] [WARNING] [] [com.hazelcast.nio.tcp.TcpIpConnection] [tid: _ThreadID=67 _ThreadName=hz._hzInstance_1_development.IO.thread-in-2] [timeMillis: 1573804804375] [levelValue: 900] [[
  [172.31.6.60]:6900 [development] [3.12] Connection[id=3, /172.31.6.60:54493->/172.31.45.154:6900, qualifier=null, endpoint=[172.31.45.154]:6900, alive=false, type=NONE] closed. Reason: Exception in Connection[id=3, /172.31.6.60:54493->/172.31.45.154:6900, qualifier=null, endpoint=[172.31.45.154]:6900, alive=true, type=NONE], thread=hz._hzInstance_1_development.IO.thread-in-2
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:113)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
]]
...
```

## Steps to reproduce 

1. Setup a k8s cluster 1.13+
2. Install Istio with mTLS
3. Apply sample manifest below

### Samples

```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payara-micro
spec:
  serviceName: payara-micro
  replicas: 2
  selector:
    matchLabels:
      app: payara-micro
  template:
    metadata:
      labels:
        app: payara-micro
    spec:
      serviceAccountName: default # need to set rbac permissions
      containers:
        - name: payara-micro
          image: payara/micro:5.193.1
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/opt/payara/payara-micro.jar"
            - "--name"
            - "$(POD_NAME)"
            - "--clustermode"
            - "kubernetes:default,payara-micro-headless"
          ports:
            - name: http-app
              containerPort: 8080
            - name: tcp-hazelcast
              containerPort: 6900
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: payara-micro-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: payara-micro
  ports:
    - name: tcp-hazelcast
      port: 6900

---
apiVersion: v1
kind: Service
metadata:
  name: payara-micro
spec:
  type: ClusterIP
  selector:
    app: payara-micro
  ports:
    - name: http-app
      port: 8080

```

## Environment ##

- **Payara Version**: 5.193.1
- **Edition**: Micro 
- **JDK Version**: 8u222-jre
- **Operating System**: Linux

**Comment by smillidge** [comment]
I have no real idea what you are trying to do here. If Istio is enforicing mutual TLS over all socket connections Hazelcast does not support that without upgrading to Hazelcast Enterprise AFAIK.

**Comment by yacut** [comment]
@smillidge Well, that's not true. [Hazelcast supports Istio mTLS with Headless k8s service](https://github.com/hazelcast/hazelcast-kubernetes/issues/118#issuecomment-553588983), but Payara doesn't. The yaml manifest above you can use to test it in k8s with Istio mTLS installed.

**Comment by smillidge** [comment]
OK I still have no idea what we are supposed to do to support Istio. Why don't we support it, is it a problem with Istio or a problem with Payara? Are you asking for an enhancement request so we support Istio? Which version of Istio should we support? Can you create a PR to provide support?

**Comment by mesutcelik** [comment]
@yacut I just removed `serviceAccount` part and it did not throw exception.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8" ?>
    <hazelcast xmlns="http://www.hazelcast.com/schema/config"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.hazelcast.com/schema/config
              http://www.hazelcast.com/schema/config/hazelcast-config-4.0.xsd">
        <network>
          <port auto-increment="false" port-count="100">5701</port>
          <join>
              <multicast enabled="false" />
              <kubernetes enabled="true">
                  <namespace>default</namespace>
                  <service-name>payara-micro-headless</service-name>
              </kubernetes>
          </join>
      </network>
    </hazelcast>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payara-micro
spec:
  serviceName: payara-micro
  replicas: 2
  selector:
    matchLabels:
      app: payara-micro
  template:
    metadata:
      labels:
        app: payara-micro
    spec:
      containers:
        - name: payara-micro
          image: payara/micro:5.193.1
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/opt/payara/payara-micro.jar"
            - "--name"
            - "$(POD_NAME)"
            - "--clustermode"
            - "kubernetes:default,payara-micro-headless"
            - "--hzconfigfile"
            - "/data/hazelcast/hazelcast.xml"
          ports:
            - name: http-app
              containerPort: 8080
            - name: tcp-hazelcast
              containerPort: 5701
          volumeMounts:
            - name: hazelcast-config
              mountPath: /data/hazelcast
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
      volumes:
        - name: hazelcast-config
          configMap:
            name: hazelcast-configuration

---
apiVersion: v1
kind: Service
metadata:
  name: payara-micro-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: payara-micro
  ports:
    - name: tcp-hazelcast
      port: 5701

---
apiVersion: v1
kind: Service
metadata:
  name: payara-micro
spec:
  type: ClusterIP
  selector:
    app: payara-micro
  ports:
    - name: http-app
      port: 8080
```

```
Payara Data Grid State: DG Version: 35 DG Name: dev DG Size: 2
Instances: {
 DataGrid: dev Instance Group: MicroShoal Name: payara-micro-0 Lite: false This: true UUID: 53262a38-eb91-4a58-b242-3abc63121624 Address: /10.60.2.22:5701
 DataGrid: dev Lite: false This: false UUID: f1c00a23-0782-4ea4-b3df-1e62f91a9a67 Address: /10.60.3.22:5701
}]]

```
