### ISSUE TITLE
Security Scheme Object in Openapi Document contains additional flows property

### ISSUE THREAD

**Issue by LarsBrenker** [payara/Payara#4791]
# Description #
----------

After generating OpenAPI Document during Payara Startup securitySchemes Defintion contains "flows" attribute which is not correct when using scheme type http with bearer jwt.

## Expected Outcome

When using HTTP Bearer JWT Security Scheme, expected outcome in OpenApi Document is

```
securitySchemes:
    http_secure:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

## Current Outcome

Actually outcome is with additional flows attribute which is wrong für HTTP Bearer JWT documented in https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#oauthFlowsObject. 

```
  securitySchemes:
    http_secure:
      type: http
      scheme: bearer
      bearerFormat: JWT
      flows: {}
```

So, Swagger Validation says

Structural error at components.securitySchemes.http_secure
should NOT have additional properties
additionalProperty: flows

## Steps to reproduce (Only for bug reports) 

Look at sample. Just put that JaxRsConfig in your App and start Payara.
Open /openapi

### Samples

´´´

@ApplicationScoped
@javax.ws.rs.ApplicationPath("/")
@OpenAPIDefinition(info = @Info(
        title = "xx",
        description = "xx",
        version = "1.0-SNAPSHOT",
        contact = @Contact(
                name = "xx",
                email = "xx")
)
)
@LoginConfig(authMethod = "MP-JWT")
@SecurityScheme(securitySchemeName = "http_secure",
        type = SecuritySchemeType.HTTP,
        scheme = "bearer",
        bearerFormat = "JWT"
)
public class ApplicationConfig extends Application {
}

´´´

## Environment ##

Payara Version: 5.201
Edition: Micro
JDK Version: Amazon Corretto 11
Operating System: Docker / Linux
