### ISSUE TITLE
Bug Report:  @SessionScoped fail with Hazelcast data grid on kubernetes using payara/micro:5.2022.1

### ISSUE THREAD

**Issue by lfpaz** [payara/Payara#5636]
# Description #

 CDI/JSF Session Beans (@Named and @SessionScoped) is not retrieved correctly by Payara micro with Hazelcast data grid in a kubernetes using a loadbalancer (nginx or traefik)  using payara/micro:5.2022.1 docker image.

## Expected Outcome ##

The (@Named and @SessionScoped) stored data should be correctly recovered during the session time.

## Current Outcome ##

If using JSF/CDI (@Named and @SessionScoped) stored data don't be showed across responses.

If the data is stored in the session directly with Servlet (request.getSession(true).setAttribute(key, value)) the data is recovered correctly.

If the app is deployed with only one POD the works correctly.

## Steps to reproduce ## 

Clone the project  https://github.com/lfpaz/test-payara-kubernetes

Compile with `mvn clean package`

Deploy the aplication https://github.com/lfpaz/test-payara-kubernetes on a k8s cluster with at least 2 POD's with a loadbalancer (nginx or traefik), using the DockerFile.

Open the app and in the "Session With CDI/JSF Test - Kubernetes"  Put some data in key and value and click "add". If the POD is changed by loadbalancer the data is not showed correctly.

Click on the link and view the same app with "Session With Servlet Test - Kubernetes". Put some data in key and value and click "add". Even if the POD is changed by the loadbalancer the data is showed correctly.

## Environment ##

- Docker image payara/micro:5.2022.1
- Rancher v1.21.9 with kubernetes v1.21.9 
- Loadbalancers - nginx or traefik 
- Deployed with self hosted gitlab
- On self hosted servers

**Comment by fturizo** [comment]
@lfpaz, I'm sorry but I tested the sample application that you've created and it works perfectly fine on a local Minikube installation. I've used the following definitions for a test deployment with 2 replicas and the corresponding service (working as a load balancer):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-demo
  template:
    metadata:
      labels:
        app: cluster-demo
    spec:
      containers:
      - name: py-micro-demo
        image: samples/web-test
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
```
 
```
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: cluster-demo
  ports:
  - name: web
    port: 80    
    targetPort: 8080
    nodePort: 30080   
``` 

I tested this scenario directly by creating port-forwards to the 2 pods on different ports and session data is correctly replicated between pods as it should. I suspect that your cluster is missing a proper service definition, which is NEEDED for the Data Grid to work correctly when using the `kubernetes` discovery mode. 

As this is not a proper Payara Micro issue and seems to be related to your Kubernetes setup, we'll proceed to close this issue as it is not covered by Community support. If you struggle with this issue you might consider getting commercial support through Payara Enterprise.
